services:
  tagistry:
    build:
      context: .
      dockerfile: Dockerfile
    image: thet4/tagistry:dev
    container_name: tagistry
    environment:
      - ROLE=default
    ports:
      - "8000:8000"
