health_strip: str = "/health"
api_strip: str = "/api"
v1_strip: str = "/v1"
send_content_file_parent_dir_strip: str = "/send_content_file_parent_dir"
send_rule_set_dir_strip: str = "/send_rule_set_dir"
send_rule_set_file_strip: str = "/send_rule_set_file"
